# Generated by Django 4.0.5 on 2022-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.DeleteModel(
            name='hello',
        ),
    ]
