# Generated by Django 4.0.5 on 2022-06-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_student_delete_hello'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='hello',
        ),
    ]
